### ISSUE TITLE
Option to Orientate Map in Direction of Travel

### ISSUE THREAD

**Issue by SDRoffey** [Xennis/green-walking#198]
Hi Fabian,
I've been using your map app for a few months and really like it. The level of detail is spot on for me. It loads the maps much quicker than any other OSM app I've found, and the satellite view is really useful.
I was wondering if you could add an option so that the map orientates itself in the direction of travel?
Many thanks,
Simon
Oxfordshire, England

**Comment by Xennis** [comment]
Hi @SDRoffey I would love to have this feature too. Similar to Google Maps where you can press the location button twice.

The issue is that the underlying library is not exposing the heading data: https://github.com/flutter-mapbox-gl/maps/issues/528 (It's only closed due to inactivity not because it was implemented). So the app doesn't get the information to rotate the map accordingly.

I'm currently checking if other libraries can do this. The issue here is that other libraries exist that can do that but don't support this kind of great detail level. One possible candidate is https://github.com/mapbox/mapbox-maps-flutter

**Comment by Xennis** [comment]
#199 switch to the new library including allowing to orientate the map in the direction of travel. This version is not released yet.

**Comment by Xennis** [comment]
Hi @SDRoffey, a new release (version 3.x) was created. The release notes:

* Click the "my location" button (bottom right) twice to turn the map into your location of travel. Click the button again to turn it off.
* Tab the map long to search what is at this location (reverse geocoding)

:tada: Thanks for your feedback and input!

The release is currently being reviewed and is **not** yet available in the Google Play store. It can take several hours or even days until Google Play reviews and rolls out a new release to all users.

**Comment by SDRoffey** [comment]
Hi @Xennis,
That is great, I look forward to trying the new version.
Thanks for the very quick response to my request!
Simon
